name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r req_new.txt

      - name: Run tests
        run: pytest tests/

  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t pcl-train .

      - name: Test Docker image
        run: docker run --rm pcl-train conda run --no-capture-output -n pcl_env pytest tests/

      # Optional: Push to Docker registry (uncomment and configure if needed)
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #
      # - name: Push Docker image
      #   run: |
      #     docker tag pcl-train ${DOCKER_USERNAME}/pcl-train:latest
      #     docker push ${DOCKER_USERNAME}/pcl-train:latest
